<!-- Footer -->
<footer>
    <div class="container text-center py-2 ">
        <p class="mb-0">
            &copy; 2026 s4160335. Your Gateway to Books.
        </p>
    </div>
</footer>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js">
</script>

<!-- Custom JavaScript -->
<script src="assets/js/scripts.js"></script>

</body>
</html>