<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="index.php">
                <span class="material-icons"> menu_book</span>
                BookVerse
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar"
                aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="mainNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php">
                        <span class="material-icons">home</span>
                        Home
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="books.php">
                        <span class="material-icons">view_list</span>
                            Browse Books
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="gallery.php">
                        <span class="material-icons">collections</span>
                            Gallery
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="add.php">
                        <span class="material-icons">add_circle</span>
                            Add Book
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>